# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aedes em Foco
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/aedesemfoco" # the subpath of your site, e.g. /blog
url: "http://lmedesenvolvimento.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
excerpt_separator: ""
incremental: true
regenerate: true

sass:
  sass_dir: _sass

gems:
  - jekyll-assets
  - jekyll-angular
  - jekyll-coffeescript
  - sass

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock

assets:
  compress:
    css:
      development: false
      production: true
    js:
      development: false
      production: true
  debug: true
  cache: .assets_cache
  cdn: false
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  autowrite: false
  autoprefixer:
    browsers: ["> 1%","last 4 versions","IE > 8"]
  assets:
    - "*.png"
    - "*.jpg"
    - "*.svg"
    - "*.eot"
    - "*.ttf"
    - "*.woff"
    - "bundle.css"
  digest: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheet
    - _assets/fonts
    - vendor
  features:
    liquid: false
    automatic_img_size: true
    automatic_img_alt : true

asset_bundler:
  compress:
    js: false
    css: false
  base_path: /bundles/
  server_url:
  remove_bundled: false
  dev: false
  bundle_name: false
  markup_templates:
    js: "<script type='text/javascript' src='{{url | prepend: site.baseurl}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url | prepend: site.baseurl}}' />\n"
